CREATE SCHEMA BANK;

CREATE TABLE BANK.ACCOUNT( ACCOUNT_NUMBER BIGINT NOT NULL PRIMARY KEY,
	ACCOUNT_NAME VARCHAR(250) NOT NULL, 
	BALANCE DOUBLE NOT NULL,
	PIN INT NOT NULL
	);
	
CREATE TABLE BANK.TRANSACTION_DETAILS( ACCOUNT_NUMBER BIGINT NOT NULL,
	TRANSACTION_TIME TIMESTAMP NOT NULL,
	TRANSACTION_AMOUNT DOUBLE NOT NULL,
	CONSTRAINT PEOPLE_PK PRIMARY KEY (ACCOUNT_NUMBER, TRANSACTION_TIME)
	);